/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    listings: Listing;
    leads: Lead;
    tasks: Task;
    deals: Deal;
    'deal-checklist-links': DealChecklistLink;
    'residential-complexes': ResidentialComplex;
    projects: Project;
    'blog-posts': BlogPost;
    services: Service;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    listings: {
      leads: 'leads';
    };
    leads: {
      tasks: 'tasks';
    };
    deals: {
      checklistLinks: 'deal-checklist-links';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    'deal-checklist-links': DealChecklistLinksSelect<false> | DealChecklistLinksSelect<true>;
    'residential-complexes': ResidentialComplexesSelect<false> | ResidentialComplexesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Сейчас в системе один пользователь-администратор. Роль «Наблюдатель» уже поддерживается схемой — на будущее, когда понадобится добавить второго человека с ограниченным доступом (например, только к заявкам).
   */
  role: 'admin' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Текстовое описание файла — для доступности и на случай, если файл не загрузится
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  title: string;
  propertyType: 'kvartiry' | 'doma' | 'dachi' | 'commercial' | 'novostroyki' | 'uchastki';
  cadastralNumber?: string | null;
  price: number;
  address: string;
  /**
   * Город/посёлок/деревня отдельно от улицы — нужно для фидов Авито/Яндекс/ЦИАН/Домклик (например «Кингисепп», «посёлок Усть-Луга», «деревня Кошкино»)
   */
  locality?: string | null;
  rooms?: ('studio' | '1' | '2' | '3' | '4' | '5plus') | null;
  /**
   * Площадь здания — для участка без построек не заполняется, см. «Площадь участка» ниже
   */
  areaTotal?: number | null;
  areaLiving?: number | null;
  areaKitchen?: number | null;
  /**
   * Площадь земельного участка в сотках (1 сотка = 100 м²) — отдельно от площади дома
   */
  areaLot?: number | null;
  floor?: number | null;
  totalFloors?: number | null;
  bathroom?: ('combined' | 'separate' | 'multiple') | null;
  balcony?: ('none' | '1' | '2' | '3plus') | null;
  renovation?: ('none' | 'cosmetic' | 'euro' | 'designer') | null;
  hasReplanning?: boolean | null;
  view?: ('yard' | 'water' | 'street' | 'park' | 'forest')[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photos?: (number | Media)[] | null;
  /**
   * Если загружено — на странице объекта появляется блок с видео (после фото) и бейдж «Видео» в каталоге. Подходит для любого видео объекта, не только с дрона
   */
  droneVideo?: (number | null) | Media;
  status: 'for-sale' | 'reserved' | 'sold';
  /**
   * Показывается на карточке лота на странице посёлка «Луга Парк». Для обычных объектов каталога оставить пустым.
   */
  badge?: ('start' | 'last') | null;
  /**
   * Заполняется только для лотов, которые должны показываться на странице проекта в разделе «Проекты». На попадание объекта в общий каталог и фиды не влияет.
   */
  project?: (number | null) | Project;
  leads?: {
    docs?: (number | Lead)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  dealType: 'sale' | 'rent';
  /**
   * Заполняется только для планировок в новостройках — привязывает объект к странице ЖК (/zhk/slug). Для обычных объектов каталога оставить пустым.
   */
  residentialComplex?: (number | null) | ResidentialComplex;
  buildingType?: ('brick' | 'panel' | 'monolith' | 'block' | 'wood') | null;
  mortgageAvailable?: boolean | null;
  /**
   * Для карты каталога и координат в фидах
   */
  lat?: number | null;
  lng?: number | null;
  publishAvito?: boolean | null;
  publishCian?: boolean | null;
  publishDomclick?: boolean | null;
  publishYandex?: boolean | null;
  gasSupply?: boolean | null;
  waterSupply?: boolean | null;
  sewerageSupply?: boolean | null;
  electricitySupply?: boolean | null;
  heatingSupply?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Латиницей, без пробелов — например «ust-luga-izhs». Страница проекта должна существовать по адресу /proekty/slug (создаётся разработчиком отдельно от карточки)
   */
  slug: string;
  coverPhoto: number | Media;
  /**
   * Фото для блока «Территория» на вручную свёрстанной странице проекта (напр. /proekty/luga-park): дороги, электричество, вид на реку. Порядок — как в списке. Для проектов без своей страницы не используется.
   */
  gallery?: (number | Media)[] | null;
  /**
   * 1-2 предложения для карточки в каталоге /proekty
   */
  shortDescription: string;
  status: 'sale' | 'development' | 'completed';
  /**
   * Необязательно — короткий текст рядом со статусом на карточке, например «Доходность 18–22%»
   */
  metric?: string | null;
  /**
   * Выключите, если карточка проекта ещё не готова к публикации
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  source:
    | 'kontakty-form'
    | 'ipoteka-calculator'
    | 'ipoteka-quiz'
    | 'katalog-obyekt'
    | 'proekt-ust-luga-izhs'
    | 'proekt-luga-park'
    | 'zhk-presentation'
    | 'other';
  message?: string | null;
  interestType?: ('personal' | 'investment') | null;
  notes?:
    | {
        text: string;
        createdAt?: string | null;
        authorEmail?: string | null;
        id?: string | null;
      }[]
    | null;
  listing?: (number | null) | Listing;
  dealStage: 'new-lead' | 'first-contact' | 'showing' | 'negotiation' | 'deposit' | 'in-progress' | 'won' | 'lost';
  tasks?: {
    docs?: (number | Task)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  consentGiven: boolean;
  /**
   * Проставляется автоматически при получении согласия
   */
  consentDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  lead: number | Lead;
  description: string;
  dueDate: string;
  done?: boolean | null;
  reminderSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residential-complexes".
 */
export interface ResidentialComplex {
  id: number;
  /**
   * Как будет показано на сайте целиком — например «ЖК «Солнечная сторона»»
   */
  title: string;
  /**
   * Латиницей, без пробелов — например «sunny-side». Страница ЖК будет по адресу /zhk/slug
   */
  slug: string;
  coverPhoto?: (number | null) | Media;
  /**
   * Необязательно — дополнительные фото ЖК для страницы /zhk/slug
   */
  gallery?: (number | Media)[] | null;
  /**
   * 1-2 предложения для карточки в каталоге /novostroyki
   */
  shortDescription?: string | null;
  /**
   * Инфраструктура, сроки сдачи, застройщик и т.д. — для страницы /zhk/slug
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  address?: string | null;
  developer?: string | null;
  status: 'planned' | 'under-construction' | 'completed' | 'frozen';
  /**
   * Выключите, если карточка ЖК ещё не готова к публикации
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: number;
  /**
   * Можно оставить пустым — при сохранении сгенерируется автоматически по участникам. Если вписать своё название, оно больше не будет перезаписываться.
   */
  title?: string | null;
  participants?:
    | {
        lead: number | Lead;
        role: 'buyer' | 'seller' | 'owner' | 'guarantor';
        id?: string | null;
      }[]
    | null;
  listing?: (number | null) | Listing;
  dealType: 'mortgage' | 'cash' | 'rent' | 'support';
  stage: 'docs-review' | 'collecting-package' | 'bank-submission' | 'rosreestr' | 'completed';
  documentsChecklist?:
    | {
        name: string;
        received?: boolean | null;
        comment?: string | null;
        id?: string | null;
      }[]
    | null;
  amount?: number | null;
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  checklistLinks?: {
    docs?: (number | DealChecklistLink)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deal-checklist-links".
 */
export interface DealChecklistLink {
  id: number;
  deal: number | Deal;
  participant: number | Lead;
  /**
   * Генерируется автоматически при сохранении — скопируйте ссылку и отправьте участнику вручную (WhatsApp/Telegram).
   */
  token?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Латиницей, без пробелов — например «sdelka-distantsionno». Статья будет по адресу /blog/slug
   */
  slug: string;
  /**
   * Необязательно — если не задана, на карточке и в превью для соцсетей используется общая заглушка
   */
  coverPhoto?: (number | null) | Media;
  category:
    'Кейсы сделок' | 'Юридические вопросы и риски' | 'Рынок недвижимости' | 'Ипотека' | 'Гид покупателя/продавца';
  /**
   * Например «3 мин» — на глаз, автоматически не считается. Необязательно.
   */
  readTime?: string | null;
  /**
   * 1-2 предложения для карточки в списке /blog и для превью в соцсетях
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Отображается на странице статьи и в разметке для поисковиков
   */
  author?: string | null;
  /**
   * Необязательный абзац сразу после даты/автора — текстом, а не карточками. Например короткое обобщение цифр статьи
   */
  tldr?: string | null;
  comparisonTable?:
    | {
        /**
         * Например «1-комнатные»
         */
        label: string;
        /**
         * Например «35 000–50 000 ₽»
         */
        range: string;
        /**
         * Например «40–45 тыс. ₽»
         */
        reference: string;
        id?: string | null;
      }[]
    | null;
  keyStats?:
    | {
        /**
         * Например «1-комнатные»
         */
        label: string;
        /**
         * Например «35 000–50 000 ₽»
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  closingQuoteText?: string | null;
  closingQuoteAuthor?: string | null;
  /**
   * Например «Яндекс»
   */
  closingQuoteSource?: string | null;
  ctaLabel?: string | null;
  publishedAt: string;
  /**
   * Выключите, если статья ещё не готова к публикации
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Например «Продажа и покупка недвижимости»
   */
  title: string;
  /**
   * Латиницей, без пробелов — например «arenda». Страница будет по адресу /uslugi/slug — этот же адрес используется для ссылок на услугу из статей блога
   */
  slug: string;
  icon: 'house-arrows' | 'house-calendar' | 'house-gear' | 'house-handshake';
  /**
   * 1-2 предложения для карточки на /uslugi и для превью в соцсетях
   */
  shortDescription: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Меньше — выше в списке карточек
   */
  order?: number | null;
  /**
   * Выключите, если страница ещё не готова к публикации
   */
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'deals';
        value: number | Deal;
      } | null)
    | ({
        relationTo: 'deal-checklist-links';
        value: number | DealChecklistLink;
      } | null)
    | ({
        relationTo: 'residential-complexes';
        value: number | ResidentialComplex;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  title?: T;
  propertyType?: T;
  cadastralNumber?: T;
  price?: T;
  address?: T;
  locality?: T;
  rooms?: T;
  areaTotal?: T;
  areaLiving?: T;
  areaKitchen?: T;
  areaLot?: T;
  floor?: T;
  totalFloors?: T;
  bathroom?: T;
  balcony?: T;
  renovation?: T;
  hasReplanning?: T;
  view?: T;
  description?: T;
  photos?: T;
  droneVideo?: T;
  status?: T;
  badge?: T;
  project?: T;
  leads?: T;
  dealType?: T;
  residentialComplex?: T;
  buildingType?: T;
  mortgageAvailable?: T;
  lat?: T;
  lng?: T;
  publishAvito?: T;
  publishCian?: T;
  publishDomclick?: T;
  publishYandex?: T;
  gasSupply?: T;
  waterSupply?: T;
  sewerageSupply?: T;
  electricitySupply?: T;
  heatingSupply?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  source?: T;
  message?: T;
  interestType?: T;
  notes?:
    | T
    | {
        text?: T;
        createdAt?: T;
        authorEmail?: T;
        id?: T;
      };
  listing?: T;
  dealStage?: T;
  tasks?: T;
  consentGiven?: T;
  consentDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  lead?: T;
  description?: T;
  dueDate?: T;
  done?: T;
  reminderSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  participants?:
    | T
    | {
        lead?: T;
        role?: T;
        id?: T;
      };
  listing?: T;
  dealType?: T;
  stage?: T;
  documentsChecklist?:
    | T
    | {
        name?: T;
        received?: T;
        comment?: T;
        id?: T;
      };
  amount?: T;
  notes?: T;
  checklistLinks?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deal-checklist-links_select".
 */
export interface DealChecklistLinksSelect<T extends boolean = true> {
  deal?: T;
  participant?: T;
  token?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "residential-complexes_select".
 */
export interface ResidentialComplexesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverPhoto?: T;
  gallery?: T;
  shortDescription?: T;
  description?: T;
  address?: T;
  developer?: T;
  status?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverPhoto?: T;
  gallery?: T;
  shortDescription?: T;
  status?: T;
  metric?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverPhoto?: T;
  category?: T;
  readTime?: T;
  excerpt?: T;
  content?: T;
  author?: T;
  tldr?: T;
  comparisonTable?:
    | T
    | {
        label?: T;
        range?: T;
        reference?: T;
        id?: T;
      };
  keyStats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  closingQuoteText?: T;
  closingQuoteAuthor?: T;
  closingQuoteSource?: T;
  ctaLabel?: T;
  publishedAt?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  shortDescription?: T;
  content?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  ctaLabel?: T;
  metaTitle?: T;
  metaDescription?: T;
  order?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}